/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.tahoo.nordnet;

import fi.tahoo.nordnet.model.OmaOsake;

public class App {

  public static void main(String[] args) {
    NordnetRobot nordnetRobot = new NordnetRobot();
    OmaOsake omaOsake = new OmaOsake();
    omaOsake.setNimi("NESTE");
    omaOsake.setMaara(37);
    nordnetRobot.myy(omaOsake);
    //nordnetRobot.checkYleisnakyma();

  }
}

/*
import com.gargoylesoftware.htmlunit.AjaxController;
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.HttpMethod;
import com.gargoylesoftware.htmlunit.Page;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.WebRequest;
import com.gargoylesoftware.htmlunit.WebResponse;
import com.gargoylesoftware.htmlunit.html.HtmlButton;
import com.gargoylesoftware.htmlunit.html.HtmlForm;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import com.gargoylesoftware.htmlunit.html.HtmlPasswordInput;
import com.gargoylesoftware.htmlunit.html.HtmlTextInput;
import com.gargoylesoftware.htmlunit.util.WebConnectionWrapper;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) throws Exception {
    java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(Level.OFF);
    try (final WebClient webClient = new WebClient(BrowserVersion.CHROME)) {
      webClient.getOptions().setJavaScriptEnabled(true);
      webClient.waitForBackgroundJavaScriptStartingBefore(5_000);
      webClient.waitForBackgroundJavaScript(3_000);
      webClient.getOptions().setCssEnabled(false);
      webClient.getOptions().setRedirectEnabled(true);
      webClient.getOptions().setUseInsecureSSL(false);
      webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
      webClient.getOptions().setThrowExceptionOnScriptError(false);
      webClient.getCookieManager().setCookiesEnabled(true);
      webClient.setAjaxController(new AjaxController());
      webClient.getOptions().setThrowExceptionOnScriptError(false);
      webClient.getCookieManager().setCookiesEnabled(true);
      final List<String> list = new ArrayList<>();

      login(webClient);
      /*
      new WebConnectionWrapper(webClient) {
        @Override
        public WebResponse getResponse(final WebRequest request) throws IOException {
          final WebResponse response = super.getResponse(request);
          String requestUrl = request.getUrl().toString();
          //System.out.println(requestUrl);

          return response;
        }
      };


      JsonElement jsonElement = GETRequest(webClient);
      JsonArray shares = jsonElement.getAsJsonObject().getAsJsonArray("shares");
      shares.forEach((JsonElement element) -> {
        JsonObject asJsonObject = element.getAsJsonObject();
        System.out.println(asJsonObject);


      });
      //webClient.waitForBackgroundJavaScript(4000);
      // HtmlPage page3 = (HtmlPage) webClient.getPage(new URL("https://www.nordnet.fi/fullscreen/viimeisimmat-kaupat/16102550"));
      //webClient.waitForBackgroundJavaScriptStartingBefore(2000);
      //  webClient.waitForBackgroundJavaScriptStartingBefore(2000);


    } catch (IOException ioe) {
      ioe.printStackTrace();
    }
  }

  private static JsonElement GETRequest(WebClient webClient) throws Exception {
    WebRequest requestSettings = new WebRequest(new URL("https://www.kauppalehti.fi/api/pages/stocklist/XHEL"), HttpMethod.GET);
    Page page = webClient.getPage(requestSettings);

    String jsonStr = page.getWebResponse().getContentAsString();
    JsonElement jsonElement = JsonParser.parseString(jsonStr);
    return jsonElement;

  }


  */

